controller_node:
  ros__parameters:

    diff_drive:
      enabled: false
      name: "diff_drive"
      max_motor_speed: 0.7
      ticks_per_rotation: 1464
      wheel_radius: 0.0625
      robot_radius: 0.2
      front_left: 1
      front_right: 3
      rear_left: 0
      rear_right: 2
      invert_left: true
      invert_right: false
      pi:
        p: 1.0
        i: 0.1
        d: 0.0
        i_max: 0.1
        i_min: 0.1

    mecanum_drive:
      enabled: false
      name: "mecanum_drive"
