uint8 command
float64 value
string sensor

uint8 GET_SENSOR = 0
uint8 GET_ANGLE = 1
uint8 LINEAR_ALIGN = 2


---
# Result
bool success
float64 value

---
# Feedback
float64 current_distance
string state